name: Build and Deploy

on:
  push:
    branches:
     - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DOCR_ACCESS_TOKEN }}
          password: ${{ secrets.DOCR_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: registry.digitalocean.com/reg-one/zenbot:latest

      - name: Deploy to DigitalOcean droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            docker login registry.digitalocean.com -u ${{ secrets.DOCR_ACCESS_TOKEN }} -p ${{ secrets.DOCR_ACCESS_TOKEN }}
            docker pull registry.digitalocean.com/reg-one/zenbot:latest
            docker stop zenbot || true
            docker rm zenbot || true
            docker run -d --name zenbot --restart unless-stopped --env-file .env registry.digitalocean.com/reg-one/zenbot:latest